name: Semgrep

on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "00 17 * * 1"

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: semgrep/semgrep:1.174.0

    # Avoid permission issues with Dependabot PRs.
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Run Semgrep CI
        run: semgrep ci --code --no-suppress-errors
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}