name: Semgrep

on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "00 17 * * 1"

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: semgrep/semgrep:1.174.0

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run Semgrep CI
        run: semgrep ci --code --no-suppress-errors
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}